-- auto Generated on 2020-06-24
-- DROP TABLE IF EXISTS `new`;
CREATE TABLE `new`(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'title',
	author VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'author',
	`time` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'time',
	comments INT (11) NOT NULL DEFAULT -1 COMMENT 'comments',
	`text` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'text',
	content VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'content',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'new';
